name: sdflabel
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip=20.0.2
  - numpy=1.16.2
  - scipy=1.2.0
  - opencv=4.1.0=py37h3aa1047_6
  - Pillow=7.2.0
  - mpi4py=3.0.3
  - numba=0.48.0
  - trimesh=3.5.19
  - pip:
    - torch==1.4.0
    - torchvision==0.5.0
    - pyquaternion==0.9.5
    - scikit_learn==0.23.2
    - open3d==0.8.0.0
